// layout оборачивает страницу (обязательный компонент)
// точка входа в приложение

import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'
import './globals.css'
// import Head from 'next/head'

// подключение шрифта (оптимальная загрузка при ssr)
const open_sans = Open_Sans({ weight: '400', subsets: ['cyrillic'] });
// подключение:
// open_sans.className - для классов / open_sans.style - для прямого style

// метаданные. имеет самый низкий приоритет и позволяет себя переопределять на уровне страниц.
// так же имеет merge эффект (объединение объектов с метаданными)
export const metadata: Metadata = {
  title: 'Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <>
    {/* <Head> // устаревший метод объявления метаданных (next v11)
		<title>Next App</title>
		<meta name="description" content="Generated by create next app" />
		<link rel="icon" href="/favicon.ico" />
	</Head> */}
	<html lang="en">
		<body className={open_sans.className}>{children}</body>
	</html>
    </>
  )
}
