// layout оборачивает страницу (обязательный компонент)
// точка входа в приложение

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Head from 'next/head'

const inter = Inter({ subsets: ['latin'] })

// метаданные. имеет самый низкий приоритет и позволяет себя переопределять на уровне страниц.
// так же имеет merge эффект (объединение объектов с метаданными)
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <>
    {/* <Head>
		<title>Next App</title>
		<meta name="description" content="Generated by create next app" />
		<link rel="icon" href="/favicon.ico" />
	</Head> */}
	<html lang="en">
		<body className={inter.className}>{children}</body>
	</html>
    </>
  )
}
